### ISSUE TITLE
Cycle number range being misrepresented in ppn notebook

### ISSUE THREAD

**Issue by adam-paul** [NuGrid/NuGridPy#1]
When running ppn in a notebook, it reads the cycles from the abu_vector directory and indicates how many "cycle numbers" were found and what they range from (see screenshot):

![cycles](https://cloud.githubusercontent.com/assets/7528109/15406469/935334b0-1dbb-11e6-8599-13b2708a94b2.png)

But if for some reason you don't have all of the cycles present in the directory, or you just have a specific selection of them that isn't necessarily chronological, the notebook will still tell you that they range from 0-n, where n is the number of cycles present in the directory minus 1. 

So for instance, in the screenshot there it says they range from 0 to 2. But actually the cycles present in the directory are cycle 0, cycle 31, and cycle 38.

**Comment by fherwig** [comment]
Yes, this is poor code design that should be fixed. ppn.py should analyze which files are there, and report them correctly. It should not make the assumption that all files are available. @adam-paul - can you fix that?

**Comment by adam-paul** [comment]
@fherwig I'll look into it, shouldn't be too much trouble

**Comment by adam-paul** [comment]
@fherwig 
This is solved with a pretty quick fix in #10 

It seems to me that there is often too much data for it to be plausible to list all of the cycle numbers available, so I left it as reporting a range. It will be obvious if there are missing cycles in between because it says how many there are total. Perhaps we could include a line that tells the user what command to issue if they wish to see exactly which cycles are available?
