### ISSUE TITLE
versioning and tagging

### ISSUE THREAD

**Issue by 2sn** [NuGrid/NuGridPy#11]
@fherwig 
How will we version NuGridPy, make (tag) releases, etc.?
Once we have the current basic version working (does it work already), we should have master and devel branches, for which we tag releases with version, and have alpha and beta releases on devel branch? New patches will be merged to develop branch, after testing, that will be merged to, or become, new master branch, a new devel branch is started.

**Comment by fherwig** [comment]
We now have a release, with version number 0.7.0, we adopt [Semantic version numbering](http://semver.org).
