### ISSUE TITLE
use of builtins and past.utils modules in mesa.py

### ISSUE THREAD

**Issue by fherwig** [NuGrid/NuGridPy#14]
@swjones  

If I use python 2.7 (via anaconda distro) I get the following error:

```
/home/fherwig/python/NuGridPy/mesa.py in <module>()
    123 from __future__ import absolute_import
    124
--> 125 from builtins import zip
    126 from builtins import str
    127 from builtins import range

ImportError: No module named builtins
```

It seems that builtins is a module only in python 3? Is it really needed to import these? Aren't the _builtins_?

If I use anaconda python distro with 3.5 I get the following error:

```
/global/home/fherwig/python/NuGridPy/mesa.py in <module>()
    126 from builtins import str
    127 from builtins import range
--> 128 from past.utils import old_div
    129 import numpy as np
    130 import numpy as np

ImportError: No module named 'past'
```

This is needed in several places, including

`def write_LEAFS_model`

which is something Sam put in? What is it doing anyways? It seems it is just doing a division? Why not use '/'?

**Comment by swjones** [comment]
Falk,

I think possibly whoever added the conversion to python 3 added this. I believe it is because the type of the result of a division (e.g. integer or float) is determined differently in python 2 and python 3. I guess someone added this to really make sure the python3 code was doing the same as the python 2 code

Sam

**Comment by fherwig** [comment]
That's fine - if `div_old` is available in the new utils. But maybe it is really not needed anymore? or the is a numpy solution to this?

**Comment by fherwig** [comment]
My error - I confused `futures` package with `future` package. It appears that with the anaconda distro the `future` package is the only things that needs to be installed by hand.
