### ISSUE TITLE
Update the nugridpy version on pypi

### ISSUE THREAD

**Issue by cphyc** [NuGrid/NuGridPy#18]
Hi,
would it be possible to upgrade the nugridpy version on pypi so that we can easily get the python3-compatible version using pip?
Thank you!

**Comment by chritter** [comment]
@cphyc The instructions for how to install the github version are in the process of being updated. Once the regression test framework of nugridpy is in place we will provide a pip3 version.

**Comment by cphyc** [comment]
Great!

Thank you very much.

**Comment by fherwig** [comment]
@cphyc NuGridPy is now available on PyPI again ... and other options, check NuGridPy home page.
