### ISSUE TITLE
Bug in mesa.py for python 3.6.1 | ipython 5.3.0

### ISSUE THREAD

**Issue by athiraam** [NuGrid/NuGridPy#27]
This line had to be changed in mesa.py for it to work in my python version, from fout=file(file_out,'w')
to fout=open(file_out,'w'). 

Thanks to Christian for helping out with this.

**Comment by nhard** [comment]
Just saw it now.

This issue is closed by #32

**Comment by fherwig** [comment]
Thanks @nhard
