### ISSUE TITLE
future translation

### ISSUE THREAD

**Issue by chritter** [NuGrid/NuGridPy#3]
@adam-paul We just checked and nugridse.py and ascii_table.py are not fully ported yet.

**Comment by adam-paul** [comment]
As in they are not fully compatible with python 3? Or they are not fully ported from the svn? What went wrong when you checked them?

**Comment by 2sn** [comment]
there were issues with tabs.  python3 only eats spaces.  (there were a few other issues as well)

I am waiting for @fherwig  to approve/check my pull request #5, a better solution to some of the modifications "utils.py --> nuutils.py" rename would be to make nugridpy a "nugrid" package.  I think I now know how to do this in a way compatible with python 3 using a __future__ import.

**Comment by 2sn** [comment]
@critter1 It would appear I should have used your branch not the master as base for my branch.
a merge should have been done (by @fherwig )
