### ISSUE TITLE
abu_profile multiple isos needed

### ISSUE THREAD

**Issue by fherwig** [NuGrid/NuGridPy#31]
[Demo notebook](
https://github.com/NuGrid/WENDI_dev/blob/master/nugridpy_issues/abu_profile%20multiple%20isos%20needed%20issue.ipynb)

**Comment by jerichooconnell** [comment]
for i in range(len(risos)):
    if logy:
        y = np.log10(abunds[i])

<===>

for i in range(len(risos)):
    if logy:
        y = np.log10(abunds if len(risos) < 2 else abunds[i])

When len(risos) = 1, meaning only one species. abunds[i] was returning a single value rather than an array of the same dimension as x
