### ISSUE TITLE
Why are we still suporting python 2.7: who uses it?

### ISSUE THREAD

**Issue by Samuel316** [NuGrid/NuGridPy#75]
I'm just wondering why we would need to support python 2? It's not like there are any complex dependencies on NuGridpy that would need to be updated first?

### But this is probably a good space for people to discuss and say why I'm wrong.

Just in case you were wondering this is what pushed me to say something:

![Screenshot from 2019-09-09 23-57-44](https://user-images.githubusercontent.com/32365597/64572146-14270980-d35e-11e9-9371-567bfcf3ad02.png)

**Comment by adam-paul** [comment]
We aren't. Python 2 has been deprecated in the refactor and won't be supported in the official release in a few months. Official python support for Python 2 also ends January 2020! So anyone reading this who is still using it should be rapidly making the transition to more modern versions right now!

**Comment by Samuel316** [comment]
Oh good you're well ahead of me.
